---
- name: Gather AIX OS system information for a single server
    hosts: 172.28.128.36   # Replace with your AIX server's inventory hostname
    gather_facts: no

    tasks:
        - name: Gather basic system facts
            ansible.builtin.setup:

        - name: Gather AIX specific system information
            ansible.builtin.shell: |
                oslevel
                uname -a
                lparstat -i
            register: aix_sysinfo

        - name: Collect memory information
            ansible.builtin.command: lsattr -El sys0 -a realmem
            register: memory_info

        - name: Collect disk information
            ansible.builtin.command: lspv
            register: disk_info

        - name: Collect network interfaces
            ansible.builtin.command: ifconfig -a
            register: net_info

        - name: Print AIX system information report
            ansible.builtin.debug:
                msg: |
                    AIX System Information:
                    ----------------------
                    OS/Kernel/LPAR Info:
                    {{ aix_sysinfo.stdout }}

                    Memory Info:
                    {{ memory_info.stdout }}

                    Disk Info:
                    {{ disk_info.stdout }}

                    Network Info:
                    {{ net_info.stdout }}
