---
- name: Password genrate on endpoint.
  hosts: all
  become: true
  gather_facts: True
  
  vars_files:
    - vars/settings.yml
  
  roles:
    - genrate_password
    
  tasks:
    - name: Generating Random password for "oxxipat1"
      ansible.builtin.set_fact:
        generated_password: "{{ lookup('passwordstore', '/dev/null length=16 chars=ascii_letters,digits') }}"
 
    - name: Display the generated password
      ansible.builtin.debug:
        msg: "Generated password for oxxipat1: {{ generated_password }}"
